/**
 * Copyright @ 2021 - 2023 JIDU AUTO CO.,LTD.
 * All Rights Reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are NOT permitted except as agreed by
 * JIDU AUTO CO.,LTD.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */

/**
 * @file
 * @brief Defines the ControllerAgent class.
 */
#pragma once

#include <cstdint>
#include <memory>
#include <unordered_map>

#include "control/src/common/control_message_stream.h"
#include "control/src/controller/controller.h"
#include "pnc_canbus_chassis.pb.h"
#include "pnc_control_cmd.pb.h"
#include "pnc_control_config.pb.h"
#include "pnc_localization_estimate.pb.h"
#include "pnc_planning.pb.h"

/**
 * @namespace jiduauto::control
 */
namespace jiduauto {
namespace control {

/**
 * @class ControllerAgent
 * @brief manage all controllers declared in control config file.
 */
class ControllerAgent {
public:
    ControllerAgent();
    ~ControllerAgent() = default;

    /**
     * @brief initialize ControllerAgent
     * @param control_conf control configurations
     * @return true if succeeded; otherwise false;
     */
    bool Init(const pnc::control::ControlConfig& control_conf);

    /**
     * @brief compute control command based on current vehicle status
     *        and target trajectory.
     * @param localization vehicle location.
     * @param chassis vehicle status e.g., speed, acceleration.
     * @param trajectory trajectory generated by planning.
     * @param cmd control command.
     * @return true if succeeded; otherwise false;
     */
    bool ComputeControlCommand(const ControlInputStream& control_input_stream, ControlCommandStream* const cmd);

    /**
     * @brief reset ControllerAgent
     * @return true if succeeded; otherwise false;
     */
    bool Reset();

    /**
     * @brief Given controller_name, get Controller.
     */
    std::shared_ptr<Controller> GetController(const pnc::control::ControlConfig::ControllerType& controller_name);

private:
    pnc::control::ControlConfig control_conf_;
    std::unordered_map<int32_t, std::shared_ptr<Controller>> controller_list_;
};

}  // namespace control
}  // namespace jiduauto
