/**
 * Copyright @ 2021 - 2023 JIDU AUTO CO.,LTD.
 * All Rights Reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are NOT permitted except as agreed by
 * JIDU AUTO CO.,LTD.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */

#include "control/src/controller/controller_agent.h"

#include "control/src/controller/chassis_test_controller.h"
#include "control/src/controller/dyn_mpc_controller.h"
#include "control/src/controller/geo_lateral_controller.h"
#include "control/src/controller/kin_mpc_controller.h"
#include "control/src/controller/lqr_lateral_controller.h"
#include "control/src/controller/pid_speed_controller_v2.h"
#include "pnc_common/src/common/pnc_logger.h"

namespace jiduauto {
namespace control {
using pnc::chassis::Chassis;
using pnc::control::ControlCommand;
using pnc::localization::LocalizationEstimate;
using pnc::planning::ADCTrajectory;

ControllerAgent::ControllerAgent() {
    controller_list_[pnc::control::ControlConfig::GEO_LAT_CONTROLLER] = std::make_shared<GeoLateralController>();
    controller_list_[pnc::control::ControlConfig::LQR_LAT_CONTROLLER] = std::make_shared<LqrLateralController>();
    controller_list_[pnc::control::ControlConfig::PID_SPEED_CONTROLLER] = std::make_shared<PidSpeedControllerV2>();
    controller_list_[pnc::control::ControlConfig::CHASSIS_TEST_CONTROLLER] = std::make_shared<ChassisTestController>();
    controller_list_[pnc::control::ControlConfig::DYN_MPC_CONTROLLER] = std::make_shared<DynMpcController>();
    controller_list_[pnc::control::ControlConfig::KIN_MPC_CONTROLLER] = std::make_shared<KinMpcController>();
}

/**
 * @brief initialize ControllerAgent
 * @param control_conf control configurations
 * @return true if succeeded; otherwise false;
 */
bool ControllerAgent::Init(const pnc::control::ControlConfig& control_conf) {
    for (auto& controller : controller_list_) {
        if (controller.second == nullptr || !controller.second->Init(control_conf)) {
            LOG_ERROR("Controller is nullptr or init failed!");
            return false;
        } else {
            LOG_INFO("Controller < %s > init done!", controller.second->Name().c_str());
        }
    }
    control_conf_ = control_conf;
    // check controller_list_ contains controller_config
    const auto& config = control_conf_.controller_config();
    if (GetController(config.lat_init()) == nullptr || GetController(config.lat_backup()) == nullptr ||
        GetController(config.lon_init()) == nullptr || GetController(config.lon_backup()) == nullptr) {
        LOG_ERROR("controller_list_ donot contains controller_config");
        return false;
    }
    return true;
}

/**
 * @brief compute control command based on current vehicle status
 *        and target trajectory.
 * @param localization vehicle location.
 * @param chassis vehicle status e.g., speed, acceleration.
 * @param trajectory trajectory generated by planning.
 * @param cmd control command.
 * @return true if succeeded; otherwise false;
 */
bool ControllerAgent::ComputeControlCommand(const ControlInputStream& control_input_stream,
                                            ControlCommandStream* const control_command_stream) {
    if (control_command_stream == nullptr) {
        LOG_ERROR("control stream invalid");
        return false;
    }
    const auto& config = control_conf_.controller_config();
    if ((config.lat_init() == pnc::control::ControlConfig::DYN_MPC_CONTROLLER &&
         config.lon_init() == pnc::control::ControlConfig::DYN_MPC_CONTROLLER) ||
        (config.lat_init() == pnc::control::ControlConfig::KIN_MPC_CONTROLLER &&
         config.lon_init() == pnc::control::ControlConfig::KIN_MPC_CONTROLLER)) {
        // Only Call once for combined controller
        if (!controller_list_[config.lat_init()]->ControlMain(control_input_stream, control_command_stream)) {
            LOG_ERROR("<%s> failed, use backup", controller_list_[config.lat_init()]->Name().c_str());
            if (!controller_list_[config.lat_backup()]->ControlMain(control_input_stream, control_command_stream)) {
                LOG_ERROR("<%s> failed, exit", controller_list_[config.lat_backup()]->Name().c_str());
                return false;
            }
            if (!controller_list_[config.lon_backup()]->ControlMain(control_input_stream, control_command_stream)) {
                LOG_ERROR("<%s> failed, exit", controller_list_[config.lon_backup()]->Name().c_str());
                return false;
            }
        }
    } else if ((config.lat_init() == pnc::control::ControlConfig::CHASSIS_TEST_CONTROLLER &&
                config.lon_init() == pnc::control::ControlConfig::CHASSIS_TEST_CONTROLLER)) {
        if (!controller_list_[config.lat_init()]->ControlMain(control_input_stream, control_command_stream)) {
            LOG_ERROR("<%s> failed, cannot generate cmd", controller_list_[config.lat_init()]->Name().c_str());
        }
    } else {
        if (!controller_list_[config.lat_init()]->ControlMain(control_input_stream, control_command_stream)) {
            LOG_ERROR("<%s> failed, use backup", controller_list_[config.lat_init()]->Name().c_str());
            if (!controller_list_[config.lat_backup()]->ControlMain(control_input_stream, control_command_stream)) {
                LOG_ERROR("<%s> failed, exit", controller_list_[config.lat_backup()]->Name().c_str());
                return false;
            }
        }

        if (!controller_list_[config.lon_init()]->ControlMain(control_input_stream, control_command_stream)) {
            LOG_ERROR("<%s> failed, use backup", controller_list_[config.lon_init()]->Name().c_str());
            if (!controller_list_[config.lon_backup()]->ControlMain(control_input_stream, control_command_stream)) {
                LOG_ERROR("<%s> failed, exit", controller_list_[config.lon_backup()]->Name().c_str());
                return false;
            }
        }
    }
    return true;
}

/**
 * @brief reset ControllerAgent
 * @return true if succeeded; otherwise false;
 */
bool ControllerAgent::Reset() {
    for (auto& controller : controller_list_) {
        if (controller.second == nullptr) continue;
        controller.second->Reset();
    }
    return true;
}

/**
 * @brief Given controller_name, get Controller.
 */
std::shared_ptr<Controller> ControllerAgent::GetController(
    const pnc::control::ControlConfig::ControllerType& controller_name) {
    auto iter = controller_list_.find(controller_name);
    if (iter != controller_list_.end()) {
        return iter->second;
    }
    return nullptr;
}

}  // namespace control
}  // namespace jiduauto
